from kynetix.solvers.kmc_plugins.coverages_analysis import CoveragesAnalysis
from kynetix.solvers.kmc_plugins.frequency_analysis import FrequencyAnalysis
from kynetix.solvers.kmc_plugins.event_analysis import EventAnalysis

